input {
  file {
    path => "/home/user/siem_logs.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{IP:source_ip} %{WORD:event}" }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "siem-logs"
  }

  stdout {
    codec => rubydebug
  }
}
